### ISSUE TITLE
Auth rate limit in Next.js Server Actions

### ISSUE THREAD

**Issue by acomanescu** [supabase/auth#1229]
I've been integrating the latest Next.js auth example and I find it extremely helpful, but there is a missing piece not documented, or not easy to find, the rate limiting when using React Server Actions.

According to the available [documentation](https://supabase.com/docs/guides/platform/going-into-prod#auth-rate-limits), rate limits are of different types. Some of them suggest that there is a rate limit based on `Request IP`, such as `Verification requests`.

If I pass the user Verification Request call to a React Server Actions, then call Supabase from the server using `createServerActionClient`, this means that all requests will have the server's IP address and it will be limited.
 
Is there any alternative or should I move everything back to the client?

**Comment by hf** [comment]
We are working on a platform fix for this, should be out in January 2024. GoTrue itself already has support for it if you're self hosting by configuring the GOTRUE_RATE_LIMIT_HEADER config variable: https://github.com/supabase/gotrue/blob/master/internal/conf/configuration.go#L203
