### ISSUE TITLE
Send `appHash` to Twilio Verify for mobile SMS OTP auto-fill-in

### ISSUE THREAD

**Issue by Kypsis** [supabase/auth#1235]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

There is no way to send the optional parameter **appHash** [(https://www.twilio.com/docs/verify/api/verification)](https://www.twilio.com/docs/verify/api/verification) when using Twilio Verify with **supabase_flutter**. This would get appended to the OTP SMS so Android could read the OTP code from SMS automatically.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## Expected behavior

A way to send **appHash** with **signInWithOtp()** method -> OTP SMS contains the appended **appHash**.

**Comment by J0** [comment]
Hey @Kypsis,

Thanks for bumping this. No tentative timeline at the moment as we're looking into custom a more general approach towards SMS providers.  If it's a hard  blocker for you I can raise it for discussion this week though.

Quick question: how is the `appHash` used after it is received in the response and is it dynamically generated?

 I don't have a strong familiarity with the `appHash` but am wondering if it be possible to manually append the `appHash`  to the message template for now if it is statically generated. 

Let me know!

**Comment by Kypsis** [comment]
App hash (signature) can be precomputed or fetched on runtime:[https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string](https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string). Then it would get get appended to the SMS via the `appHash` optional parameter when doing POST request to `https://verify.twilio.com/v2/Services/{ServiceSid}/Verifications`. On an Android device the SMS Retriever API would read the OTP from SMS automatically via the `appHash` identifier in the SMS response and would then allow for the OTP auto-fill functionality to work. Which leads to very nice frictionless UX for the user.

**Comment by Kypsis** [comment]
Any progress on this issue?

**Comment by J0** [comment]
Hey @Kypsis,

Thanks for waiting, we are working on a solution for this  via auth hooks and it'll probably land close to our next launch week in December. Do check back then and lmk if there are any immediate concerns.

**Comment by hf** [comment]
Until we have this, feel free to open a PR and the team will prioritize reviews.

**Comment by J0** [comment]
Hey,

This should be achievable now with the [send sms](https://supabase.com/docs/guides/auth/auth-hooks/send-sms-hook) hook. Going to close for now but feel free to re-open if there are still issues

Thanks
Joel
