### ISSUE TITLE
Supabase auth for case sensitive emails

### ISSUE THREAD

**Issue by Preetam7064** [supabase/auth#1414]
It is still an issue if "Jason@example.com" exists and if we signup with email "jason@example.com" using const { user, error } = supabase.auth
.signUp() it doesn't giving error rather creating another user with different user_id. And it is not visible in supabase auth listing as well

**Comment by MeyerOppelt** [comment]
While it wouldn't fix the supabase-auth issue, is it possible to always convert the email to lowercase in your client?

**Comment by kangmingtay** [comment]
@Preetam7064 @MeyerOppelt emails are always treated as case-insensitive in supabase auth - we don't have plans on making them case sensitive

**Comment by Preetam7064** [comment]
> @Preetam7064 @MeyerOppelt emails are always treated as case-insensitive in supabase auth - we don't have plans on making them case sensitive

Try using such email you will get as it is creating issue
