### ISSUE TITLE
Fix broken link to inexistant netlify github repo

### ISSUE THREAD

**Issue by AntonOfTheWoods** [supabase/auth#1492]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://github.com/supabase/gotrue)

## Describe the problem

The mass rename renamed "gotrue" to "auth", including for the original netlify repo. `netlify/auth` doesn't exist

## Describe the improvement

Point to `netlify/gotrue`

## Additional context

Fixed by https://github.com/supabase/gotrue/pull/1491

**Comment by J0** [comment]
Closing  as it seems fixed but let us know if there are any remaining concern
