### ISSUE TITLE
Can't send OTPs with MessageBird for Auth - access key invalid

### ISSUE THREAD

**Issue by katherineqian** [supabase/auth#1554]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I keep receiving the 422 response `Request not allowed (incorrect access_key)` even when a cURL request with the same access key from MessageBird is succeeding. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://app.bird.com/settings/security/access-keys to generate an access key as described in the docs. 
2. Get an access key with permissions for creating and viewing from `/workspaces/*/channels/*/messages` as described in Messagebird docs.
3. Try making a cURL request to send a text message with the generated key. Observe that the request succeeds.
5. Try sending an auth OTP using the same key entered into the Supabase dashboard. Observe that the request fails with `Request not allowed (incorrect access_key)`.

## Expected behavior

OTP should send to the desired phone number if the access key is working elsewhere.

## Screenshots

N/A

## System information

- OS: Flutter on MacOS
- Browser (if applies) [e.g. chrome, safari]: N/A
- Version of supabase-js: Using supabase_flutter: ^2.3.4
- Version of Node.js: N/A, using supabase_flutter: ^2.3.4

**Comment by MichaelKirsch** [comment]
Same problem here

**Comment by kangmingtay** [comment]
Hey @katherineqian and @MichaelKirsch, it seems like the change from messagebird to bird caused the integration to break here - the messagebird SMS provider was added quite awhile back (https://github.com/supabase/auth/pull/210) and is only compatible with the old API.

**Comment by h8f1z** [comment]
@kangmingtay Any idea when the issue will be resolved?

**Comment by Ozzy1997** [comment]
hello there is there a fix fro this ?

**Comment by levismithxyz** [comment]
any fixes for this?

**Comment by kangmingtay** [comment]
Hi everyone, as mentioned previously, there seems to be some incompatibility between MessageBird's API and their API after they rebranded to Bird. 

We recently launched a hook for sending SMS, if you want to use Bird as the SMS provider, you can use the hook to directly make requests to their API endpoint. Here are some links which may be useful:
- [Blog post](https://supabase.com/blog/third-party-auth-mfa-phone-send-hooks#auth-hooks-for-sms-and-email)
- [Guide for implementing the SMS hook](https://supabase.com/docs/guides/auth/auth-hooks/send-sms-hook?queryGroups=language&language=http)

**Comment by J0** [comment]
Hey team,

Going to close but feel free to comment, or open a ticket if there are any issues with implementing the provider.

**Comment by avocadodip** [comment]
Would love to see this fixed!

**Comment by lubuggiano** [comment]
> Would love to see this fixed for the new API!

Me too!

**Comment by pnavk** [comment]
Given this was reported over a year ago....the docs need to be updated to reflect that the MessageBird Phone Provider no longer works and requires Auth Hooks instead. Additionally, having Messagebird as a valid provider in the Phone Provider configuration (and config.toml) is really misleading.

For other using MessageBird: **[here](https://www.pranavkhandelwal.com/blog/2025/6/1/supabase-otps-with-bird-formerly-messagebird-in-2025)** is a code example to get SMS OTP working with MessageBird.

**Comment by h8f1z** [comment]
> Was this resolved? I'm having the same problem!

I'm not sure. I replaced supabase with my own API.

**Comment by Uri6** [comment]
+1

**Comment by Uri6** [comment]
Hey @kangmingtay please review my PR

**Comment by mklb** [comment]
+1
