### ISSUE TITLE
auth.sms.test_otp w/ international numbers

### ISSUE THREAD

**Issue by franzwarning** [supabase/auth#1566]
Hi! I'm trying to use test_otp codes via `signInWithOtp` for international phone numbers, but it doesn't seem to work when I have a number that is prefixed with `+1...`. Has anyone else seen this behaviour?

**Comment by kangmingtay** [comment]
hey @franzwarning, thanks for reporting this, we've made a fix for it - the issue is due to the auth service not applying the same basic formatting rules for the test OTPs in the config but it does not affect the SMS delivery to the underlying provider used (the country code will be respected)

**Comment by franzwarning** [comment]
Thank you for the fast response!

**Comment by choim4389** [comment]
I facing error `(last key "auth.sms.test_otp"): expected '.' or '=', but got '+' instead` when try to set test_otp in config.toml for local development.

```[auth.sms.test_otp]
+821012341234 = "012345"`

**Comment by encima** [comment]
@choim4389 wrap the phone number in quotes as well
