### ISSUE TITLE
Bad migration crashing server

### ISSUE THREAD

**Issue by lhotwll217** [supabase/auth#1570]
# Bug report
Gettign this error on my hosted instance. This is a bit puzzling. Server keeps trying to reinitialize and failing here.

{"level":"fatal","msg":"running db migrations: error executing migrations/20221208132122_backfill_email_last_sign_in_at.up.sql, sql: -- previous backfill migration left last_sign_in_at to be null, which broke some projects\n\ndo $$\nbegin\nupdate auth.identities\n  set last_sign_in_at = '2022-11-25'\n  where\n    last_sign_in_at is null and\n    created_at = '2022-11-25' and\n    updated_at = '2022-11-25' and\n    provider = 'email' and\n    id = user_id::text;\nend $$;\n: ERROR: operator does not exist: uuid = text (SQLSTATE 42883)","time":"2024-05-04T20:06:01Z"}

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment]
https://github.com/orgs/supabase/discussions/20722

**Comment by kangmingtay** [comment]
closing because it's been addressed in the discussion

**Comment by Tananga** [comment]
I have the same issue

**Comment by VitaliyHula** [comment]
I have the same issue
This happened after the first user registered via email and password.
Until that moment, we had no users who were registered via email and password

**Comment by StoneTapeStudios** [comment]
We were encountering the same issue and resolved it by stopping supabase and deleting the volumes. This can be done from the Volumes tab in Docker Desktop or with the command `docker volume rm $(docker volume ls -q | grep supabase)`
