### ISSUE TITLE
Updating a user's password kills their session

### ISSUE THREAD

**Issue by haydn** [supabase/auth#1579]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Historically, when the `PUT /admin/users/:id` route was used to change a user's password (maybe other fields too — I've only tested changing passwords) their current session would not be affected. In the latest version (somewhere after v2.149) their session is immediately killed and they must re-authenticate.

This may have been an intentional change, but it appears to have caused problems for a number of people. I've included a workaround for others hitting this issue.

## To Reproduce

I am only able to see this behaviour using the Supabase hosted platform (it's affecting our staging and production apps, but is not present in our development environments). If I connect my local app to the CLI Supabase instance (CLI v1.165 which ships with GoTrue v2.149) then I cannot see this behaviour, if I connect it to a hosted Supabase instance I can see this behaviour.

Here's a simplified version to reproduce with a hosted instance:

1. Create a user with just an email (`POST /admin/users`).
2. Generate a OTP link for that user (`POST /admin/generate_link`).
3. Verify user with OTP (`POST /verify`).
4. Update that user's password (`PUT /admin/users/:id`).

After step 3 the user has a session, but after step 4 the user no longer has a session.

## Expected behaviour

In earlier versions (such as v2.149) the user's session would not be affected by their password being updated.

## Screenshots

N/A

## System information

This is on the Supabase hosted platform — I'm not sure of the GoTrue version. Is there somewhere I can see the version numbers in the dashboard? 🤷

## Additional context

Issues/discussions that are possibly related:

- https://github.com/orgs/supabase/discussions/23715
- https://discord.com/channels/839993398554656828/1235896967754682478/1235896967754682478

Terms people hitting this issue might be searching for:

- `updateUserById`
- `Session from session_id claim in JWT does not exist`

## Workaround

In my case, to retain the historical behaviour, we can re-authenticate the users immediately after the password is updated by signing them in again with `supabase.auth.signInWithPassword()` (`POST /token?grant_type=password`).

**Comment by hf** [comment]
This is 100% expected and correct behavior. If a user's password changes, they must be logged out of all places. The user's password didn't change for no reason. For example, suppose the user learns that someone has access to their password and they take action to change it.

The only way to "kick out" the would-be attacker is to revoke all sessions for the user.

**Comment by haydn** [comment]
@hf Thanks! Good to know this was an intentional change to the platform.

I've said this before about other issues I've run into — it's really frustrating that changes get applied to the production environment before the CLI is updated (or even has a way to use the latest version). It means in situations like this it's impossible to reproduce the behaviour locally until the CLI happens to get updated to the latest version. I'll open issue over on the CLI repo about it.

**Comment by hf** [comment]
> Also note this is a breaking change since the original behavior has been changed because before you wouldn't be logged out previously and now you are being logged out.

It's not a breaking change if the previous behavior was buggy and especially in this case as it pertains to security. 

> I don't remember being logged out of other services when I do a password change.

It's done like this pretty much everywhere. It's [industry best practice also](https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html#user-resets-password).

> then hits submit and is now signed out

Is this really true? The code is to log all _other_ sessions: https://github.com/supabase/auth/blob/master/internal/api/user.go#L185

**Comment by silentworks** [comment]
> It's not a breaking change if the previous behavior was buggy and especially in this case as it pertains to security.

If previously it behaved one way and then that behavior has changed even if for security reasons it's a breaking change.

> It's done like this pretty much everywhere. It's [industry best practice also](https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html#user-resets-password).

This is talking about forgot password, not update password. These are two different things although Supabase treats both as the same thing.

> Is this really true? The code is to log all other sessions: https://github.com/supabase/auth/blob/master/internal/api/user.go#L185

I haven't tested this, but going off what's described by OP and the reply you gave I would assume this is true. I will try and get a test project setup to see if this behavior is as I've described.

**Comment by hf** [comment]
> If previously a public API behaved one way and then that behavior has changed even if for security reasons it's a breaking change.

It's not a breaking change if a bug/security issue was fixed. This behavior should have been expected. If there's a problem with a flow not working as intended -- not super clear if that's the case as the code _will not log out the user causing the password change_, then there's not much further to discuss.

**Comment by haydn** [comment]
It was killing the "current" session for me… but maybe that's because the password update was being done via the admin API using the service role? I'm assuming the user's session would be considered a different session than the admin role?

**Comment by hala94** [comment]
@haydn 

Try using the "regular" api to update a password.
And "admin" api to do the rest. 

Session should be intact then.
