### ISSUE TITLE
REST API documentation consistency improvements

### ISSUE THREAD

**Issue by alexvuka1** [supabase/auth#1590]
I have identified the following possible instances of inconsistencies between [Open API specification](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml) and [Documentation](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/README.md):

- ### 🟩Found in Open API specification, 🟥Not found in Documentation
	- [ ] [`POST /resend`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`POST /factors`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`POST /factors/{factorId}/challenge`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`POST /factors/{factorId}/verify`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`DELETE /factors/{factorId}`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`POST /callback`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`POST /sso`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`GET /saml/metadata`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`POST /saml/acs`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`POST /generate_link`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`GET /admin/audit`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`GET /admin/users`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`GET /admin/users/{userId}/factors`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`PUT /admin/users/{userId}/factors/{factorId}`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`DELETE /admin/users/{userId}/factors/{factorId}`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`GET /admin/sso/providers`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`POST /admin/sso/providers`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`GET /admin/sso/providers/{ssoProviderId}`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`PUT /admin/sso/providers/{ssoProviderId}`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`DELETE /admin/sso/providers/{ssoProviderId}`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`GET /health`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`GET /admin/users/{userId}`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
	- [ ] [`DELETE /admin/users/{userId}`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml)
- ### 🟥Not found in Open API specification, 🟩Found in Documentation
	- [ ] [`POST /admin/generate_link`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/README.md?plain=1#L783)
	- [ ] [`POST /admin/users/<user_id>`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/README.md?plain=1#L759)
- ### 🟩Found in Open API specification, 🟩Found in Documentation, 🟥Have Inconsistencies
	- | Inconsistency type | Open API specification <br /> [`POST /reauthenticate`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/openapi.yaml) | Documentation <br /> [`GET /reauthenticate`](https://github.com/supabase/auth/blob/b954a485096cddfd1eef4d582034a99eff95fa6f/README.md?plain=1#L1163) |
		| --- | --- | --- |
		| Method mismatch | `POST` | `GET` |

**About**

This is part of the evaluation of my Master's Project at Imperial College London. The section above is automatically generated and aims to expose API documentation inconsistencies in real-world GitHub repositories. The end goal is for the tool to be used as part of CI/CD, namely as a GitHub action. 

Hopefully, this is a step towards easier maintenance of API documentation. If you find this helpful, please consider updating the documentation to keep it in sync with the source code. I am also happy to assist with it, if appropriate. If this has not been useful, consider updating this issue with an explanation, so I can improve my approach. Thank you!

**Comment by hf** [comment]
Please avoid using only automated tools without human review. 

The OpenAPI spec _is the documentation._ Not everything is for README, and Supabase docs usually exist in https://supabase.com/docs.

**Comment by alexvuka1** [comment]
Thank you for your feedback, @hf . I appreciate the clarification that the OpenAPI spec serves as the primary documentation and that not all endpoints are intended for the README. However, it does seem that the OpenAPI spec and the README have at least some overlap.

I understand the concern about relying solely on automated tools without human review. However, the intention behind this tool is to assist maintainers by identifying potential discrepancies that might otherwise be overlooked, thus facilitating a more efficient review process. Here are a few points to consider in defense of this approach:

1. Efficiency: Automated tools can quickly scan and compare large documents, identifying inconsistencies in a fraction of the time it would take a human. This allows maintainers to focus their efforts on verifying and correcting issues rather than identifying them.
1. Scalability: As projects grow, the documentation tends to become more complex. An automated tool can scale with the project, ensuring continuous monitoring of documentation consistency across all updates.
1. Support for Human Review: The tool is designed to support, not replace, human review. By flagging potential issues, it provides a starting point for maintainers to perform more detailed examinations and make informed decisions.

Additionally, this tool is still in the development process, and the purpose of raising this issue is to gather feedback on how to make it better. Input from experienced teams like yours is invaluable in fine-tuning the tool to ensure it aligns with practical needs and workflows. Your insights can help refine its functionality, making it a more effective and reliable asset for documentation maintenance.

To make this tool more effective and aligned with your practices, any specific guidance on how you differentiate which endpoints should be included in the README versus the OpenAPI spec would be very valuable. 

Thank you for considering these points and also thank you @bnjmnt4n for acknowledging the identified inconsistencies. I'm eager to refine this tool to better support your documentation maintenance process and ensure it complements the excellent work your team is doing.
