### ISSUE TITLE
With email verification disabled in my project, email verification is still required in order to promote an anonymous user

### ISSUE THREAD

**Issue by symbolpunk** [supabase/auth#1619]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

With email verification disabled in my project, email verification is still required in order to promote an anonymous user (created via `signInAnonymously`) to a non-anonymous user (via `auth.updateUser({ email })`.

## To Reproduce

1. Disable email verification in your project.
2. Create an anonymous user via `auth.signInAnonymously()`.
3. Attempt to link the anonymous user to an email identity via `auth.updateUser({ email })` per instructions found in your [docs](https://supabase.com/docs/guides/auth/auth-anonymous) and [blog post](https://supabase.com/blog/anonymous-sign-ins).

## Expected behavior

 - If I've disabled email verification, I expect email verification to be disabled globally, in all scenarios, along all paths.
 - If this is a known limitation, it ought to be disclosed in the [docs](https://supabase.com/docs/guides/auth/auth-anonymous) and [blog post](https://supabase.com/blog/anonymous-sign-ins).

## Additional context

 - This is blocking us from migrating from Firebase. It would be wonderful to understand whether this can be prioritized, an ETA for a fix, and/or possible workarounds that do not require email linking to emit a verification email.
 - Devs may encounter "Updating password of an anonymous user is not possible" when attempting to set a user's password via `auth.updateUser({ password })` per your docs, _after_ attempting the `auth.updateUser({ email })` call.
 - The current, buggy `updateUser` flow appears to write the supplied `email` to `email_change` instead of `email` on the anonymous user's row in the `auth.users` table.
    - This suggests that the bugfix would involve referring to the project settings, and then if email verification is disabled, set `email` and `email_confirmed_at` accordingly, while triggering whatever additional business logic is required to promote the anonymous user, without emitting an email or requiring email verification.

**Comment by kangmingtay** [comment]
hey @symbolpunk, 

> This is blocking us from migrating from Firebase.

can you elaborate on why this is a blocker for migrating from Firebase?

> Devs may encounter "Updating password of an anonymous user is not possible" when attempting to set a user's password via auth.updateUser({ password }) per your docs, after attempting the auth.updateUser({ email }) call.

This is the current limitation and we're working to see how this can be improved. Currently, an anonymous user will need to verify the email change first before calling `updateUser` to add a password.

> The current, buggy updateUser flow appears to write the supplied email to email_change instead of email on the anonymous user's row in the auth.users table.

yeah, it doesn't respect the email verification disabled config and this seems like a bug - i'll check with the team if there are any concerns before making a fix for this

**Comment by NodeAdam** [comment]
This is a blocker for projects that want minimal friction, which is the purpose of anonymous logins

**Comment by kangmingtay** [comment]
hey @symbolpunk and @NodeAdam, this took some time as the team was quite tight on bandwidth, but i've just put a PR up for it, thanks for reporting this!
