### ISSUE TITLE
docker image version of `supabase/auth` not updated

### ISSUE THREAD

**Issue by BjoernRave** [supabase/auth#1625]
You renamed this project from gotrue to auth and therefore also released another docker build. However the new `auth` image was last updated 6 months ago.

![Screenshot 2024-06-18 at 11 57 10](https://github.com/supabase/auth/assets/36173920/960181d0-209c-4f9c-93ea-bea2ca1e9a0a)

**Comment by J0** [comment]
Hey we'll look at this in a bit but in the meantime could you try using the [DockerHub repo](https://hub.docker.com/r/supabase/auth/tags) ?

Thanks!
