### ISSUE TITLE
JWT aud claim suddenly an array instead of string

### ISSUE THREAD

**Issue by lauri865** [supabase/auth#1656]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The JWT's "aud" claim is an array instead of a string all of a sudden (authenticated through Google Oauth flow fwiw), which has broken our custom backend's JWT verifier overnight (we haven't committed any changes on our end to this project in months, nor do we use any auth hooks):
<img width="315" alt="Screenshot 2024-07-12 at 12 19 48" src="https://github.com/user-attachments/assets/8dac8395-ebfa-41ff-87bd-432b5700ba11">

Has there been a breaking change or is this a bug?

Support Ticket ID: 2955403285

**Comment by barrownicholas** [comment]
I believe this was fixed in #1657

**Comment by kangmingtay** [comment]
@lauri865 apologies for the breaking change introduced, we have set up some E2E tests as well to validate the JSON schema of the JWT payload to prevent this from happening in the future

closing this PR since it was fixed in #1657
