### ISSUE TITLE
signInWithPassword does not return an error code when the login credentials are invalid

### ISSUE THREAD

**Issue by moralestapia** [supabase/auth#1662]
I confirm this is a bug with Supabase, not with my own application. 
I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Most (all?) other supabase.auth methods return a code property in the error object, if there's any, as documented [here](https://supabase.com/docs/reference/javascript/auth-error-codes).

supabase.auth.signInWithPassword does not, for some reason, and one has to check if the error message property is equal to "Invalid login credentials".

This breaks consistency across the platform and makes people write code that may not be future-proof. If error.message changes then it's gg, while error.code somehow implies a guarantee of stability across time.

## To Reproduce

await supabase.auth.signInWithPassword({ email:[some valid email], password:[some invalid password] });

## Expected behavior

An error object with a defined code property.

## Screenshots

N/A

## System information

@supabase/ssr@0.1.0
@supabase/supabase-js@2.43.5

Node version: 20.15.0

## Additional context

I < 3 supabase.

**Comment by kangmingtay** [comment]
jfyi, this is identical to https://github.com/supabase/auth/issues/1631

**Comment by encima** [comment]
Well then, let's close in favour of tracking it there!

**Comment by swdevbali** [comment]
Any update on this? This hard to debug as it occur to some random user

**Comment by Kleboia** [comment]
hello i have the same issue when using a wrong password or non existing email. do you have some update ?
