### ISSUE TITLE
Missing sms type?

### ISSUE THREAD

**Issue by pauldemarco** [supabase/auth#1681]
https://github.com/supabase/auth/blob/f9df65c91e226084abfa2e868ab6bab892d16d2f/openapi.yaml#L199

**Comment by J0** [comment]
Hey! 

Thanks for the feedback. Not sure if I'm understanding this correctly but if it's for the GET endpoints we don't support `phone_change` and `sms` on the endpoint. We only support `phone_change` and `sms` on POST `/verify`

Going to close but feel free to re-open if I've misunderstood
