### ISSUE TITLE
Apple Auth (Web) - Sign up not complete

### ISSUE THREAD

**Issue by chanmathew** [supabase/auth#1706]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Hi folks,

I've followed the guide here to setup Apple Auth but have been stumped for days (https://supabase.com/docs/guides/auth/social-login/auth-apple?queryGroups=environment&environment=client&queryGroups=framework&framework=sveltekit&queryGroups=platform&platform=web#configuration-web). I am getting a "Sign up not complete" error when the prompt comes up. This is the case whether I choose Share or hide my email.

Please see below screenshots. What am I missing?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Followed the guide step by step (see screenshots below)
2. Built the iOS app
3. Tested on real device, sign up prompt comes up
4. Receive error about "Sign up not complete"

I'm building my native app with CapacitorJS (6.0.0) and Sveltekit (2.5.18).

Here's the code in my Sveltekit app, on the /auth page where I have a Continue with Apple button to sign up:
```ts
const platform = Capacitor.getPlatform()

// Return a deeplink redirect on mobile, otherwise regular path
const getURL = () => {
if (platform !== 'web') {
	return 'talewind://?slug=saved'
}
return '/saved'
}

async function handleAppleAuth() {
		const { data, error } = await supabase.auth.signInWithOAuth({
			provider: 'apple',
			options: {
				redirectTo: getURL()
			}
		})

		if (error) {
			console.log(error)
			throw error
		}
	}
```

## Expected behavior

Apple auth should authenticate correctly and redirect to the app after successful sign up or sign in.

## Screenshots

I've setup the Primary App ID:
![CleanShot 2024-08-02 at 16 45 14@2x](https://github.com/user-attachments/assets/2b7162cb-3f8e-403b-9748-a6528642aa90)

Then I enabled Sign In with Apple on the App ID, and left the server-to-server notification endpoint blank as per the guide:
![CleanShot 2024-08-02 at 16 46 19@2x](https://github.com/user-attachments/assets/fac2d4ab-50ec-4051-a501-b643f388d2c4)

Then I've setup the Service ID:
![CleanShot 2024-08-02 at 16 48 55@2x](https://github.com/user-attachments/assets/7cc9a8d0-e16a-4ef8-a809-e65a29ad9861)

And I've configured the Sign In with Apple with the Service ID, adding in the correct domain, and return URLs as specified from the guide:
![CleanShot 2024-08-02 at 16 50 41@2x](https://github.com/user-attachments/assets/7c08c948-c3f1-4729-9ef7-135b5cb4c231)

I've setup the Auth Key, downloaded the p8 file and used the tool in the guide to generate the secret:
![CleanShot 2024-08-02 at 16 47 11@2x](https://github.com/user-attachments/assets/65201701-f131-4e00-b7d1-b13c454fe6f9)

Then I put everything in the cloud Supabase dashboard:
![CleanShot 2024-08-02 at 16 33 02@2x](https://github.com/user-attachments/assets/9cba6d09-125e-4f2e-ae5c-a5f7a560ab88)

When I build my iOS app, this is the error that I get when I try to sign in:
![apple-cannot-sign-in](https://github.com/user-attachments/assets/c8097b9d-47c8-4d67-a1ff-32fcee60024d)

## System information

- OS: iOS
"@supabase/supabase-js": "^2.44.2"
Node: 20.15.1

**Comment by chanmathew** [comment]
Nvm, realized the service ID identifier is backwards in my Developer account 🤦

**Comment by berkingurcan** [comment]
> Nvm, realized the service ID identifier is backwards in my Developer account 🤦

I have the same issue, what does it mean?
