### ISSUE TITLE
code and code verifier issue in documentation using nextjs Oauth(GoogleSigin)

### ISSUE THREAD

**Issue by Hussain101** [supabase/auth#1718]
# Improve documentation

Add a link to the page which needs improvement (if relevant)

https://supabase.com/docs/guides/auth/social-login/auth-google?queryGroups=environment&environment=client&queryGroups=framework&framework=nextjs

Hey!
I am using auth with Google using nextjs so according to your documentation, there is just only a need for code return in the URL query parameter by Google.  But I was continuously facing the issue of invalid codeVerifier and code and codeVerifier can't be empty. In your documentation, there is nothing mention about the codeVerifier.

I have run the code by generating the code verifier manually, let's chat to discuss this in detail.
My email is hussainsidd88@gmail.com

Thanks

**Comment by kangmingtay** [comment]
hi @Hussain101, please open a support ticket with us at https://supabase.help - it will make things alot easier for us to track and investigate the issue

**Comment by Hussain101** [comment]
Hey @kangmingtay!
I have created the ticket, you can check and let me know
