### ISSUE TITLE
HookName field unavailable in the UI, thus not saved in backend.

### ISSUE THREAD

**Issue by deezeddd** [supabase/auth#1734]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

**HookName** isn't available in the Hooks(UI) although, it is present in the struct. Kindly have a look here => https://github.com/supabase/auth/blob/master/internal/conf/configuration.go#L640

I've also verified the response we get after creating a hook from UI. 

```
{
  "HOOK_SEND_EMAIL_ENABLED": false,
  "HOOK_SEND_EMAIL_URI": "https://localhost:3000",
  "HOOK_SEND_EMAIL_SECRETS": "any_secret"
}

```
The above is what we send as a payload, I couldn't even find anything related to HookName in the response too. Is HookName to be implemented in the coming releases or is user restricted to add hookName. 
 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the Hooks in Auth Tab from UI.
2. Create a hook
3. **Er**r - HookName isn't available

## Expected behavior

If correct, then the hookName should be available to be added by the user via the UI.

## Screenshots

N/A

## System information

- OS: MacOS
- Browser : Arc
- Version of supabase-js: Doesn't Apply
- Version of Node.js: Doesn't Apply

### Suggestion : A check for all the entities might help in future

**Comment by kangmingtay** [comment]
hi @deezeddd , i can't seem to reproduce this error when i attempt to add a postgres / http hook from the dashboard - can you provide more information about how you're seeing this error message?

**Comment by deezeddd** [comment]
Hi, there isn’t error thrown. The field hookName is available in backend which is supabase/auth but not on the frontend to edit

**Comment by kangmingtay** [comment]
@deezeddd does it impact the usability of the hook here? also, is there a reason why you need to set the hook name explicitly through the UI? 

i can't remember why we made the decision not to expose it but i'll check with the team on this and get back to you

**Comment by deezeddd** [comment]
@kangmingtay that’s what I’m confused about why it is needed at the first place when it’s not in use, this might create a confusion in long term I believe. 
If there is feature that might get implemented in future then it’s not a problem.

**Comment by J0** [comment]
Hey @deezeddd,

Thanks for the query and for raising this - the HookName is generated from the `Postgres URI` and used internally to invoke the hook. 

A secondary consideration was that we'd eventually expose the HookName with HTTP Hooks and  allow developers to edit the name of the hook so that they can correlate with events / logs. I'm not sure if we still plan to proceed with this though.

We'll either add a comment in the code or note in the docs to clarify this.

**Comment by deezeddd** [comment]
Thanks, @J0 and @kangmingtay for helping with the query, adding a comment will be great! 
Exposing the HookName is what **I thought** was about to be done in future updates. Thank you for clarifying this. I will mark the issue close.

**Comment by J0** [comment]
Thanks for raising! I'll follow up with a PR either adding a comment or omitting the field entirely from serialization.
