### ISSUE TITLE
Auth - Error sending magic link - Status 500

### ISSUE THREAD

**Issue by jellohouse** [supabase/auth#1740]
## BUG

Out of the blue, email login with magic link stopped working.

When the POST request to `https://xxxxxx.supabase.co/auth/v1/otp?redirect_to=example.com`  to create the magic link email is sent, the browser receives a status 500 with response:
```
{ "code": "unexpected_failure", "message": "Error sending magic link" }
```

I have 2 projects using this auth method with supabase and both are giving this error.

Although both projects are using Resend SMTP... but it seems like there is no issue there.

## To Reproduce

Launch a project using Supabase auth passwordless sign in.
For example: https://github.com/vercel/nextjs-subscription-payments

## Expected behavior

Magic link email should be sent.

**Comment by davidd8** [comment]
I am seeing this issue in production for my app as noted in https://github.com/orgs/supabase/discussions/29370#discussioncomment-10781347
