### ISSUE TITLE
PUT /USER is abusable

### ISSUE THREAD

**Issue by ZhenFTW** [supabase/auth#1772]
# Bug report
Hi i just notice that the PUT /USER  endpoint can be abused for adding putting data.

![image](https://github.com/user-attachments/assets/653055d9-b83e-409b-8054-cb75b67c0d14)
 

is it intended?

**Comment by ZhenFTW** [comment]
this can be abused by anyone just because everyone authenticated can access this endpoint and they can flood the  /PUT user endpoint to set user data.

**Comment by cstockton** [comment]
Thanks for the report, while this conscience design decision makes Supabase powerful you make a good point that it puts some responsibility on users to have good RLS policies. I'll discuss with team to see if there are opportunities for better documentation / user education. I don't think that changing defaults is on the table though.
