### ISSUE TITLE
Email hook = duplicated auth emails

### ISSUE THREAD

**Issue by Bartek532** [supabase/auth#1781]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I set up an `send_email` hook, which is sending an email from my third-party provider (Resend). But I constantly receive emails sent by Supabase automatically, so I'm receiving two emails now (e.g. for confirming account). Can I solve it somehow (e.g. by disabling Supabase emails)?

## Expected behavior

One email is delivered to the user.

**Comment by J0** [comment]
Hey,

Thanks for flagging the issue. Do you mind opening a ticket at [supabase.help](supabase.help)? If you could include the edge function code that would be helpful as well - there should only be one email sent. You can mention this issue in the ticket

**Comment by J0** [comment]
Hey @Bartek532,

Thanks for writing back and apologies for the delay - if you could open a ticket that would be great as it would provide more information for debugging. You can mention that we had this convo for a faster response.

Thanks
Joel

**Comment by Bartek532** [comment]
> Hey @Bartek532,
> 
> Thanks for writing back and apologies for the delay - if you could open a ticket that would be great as it would provide more information for debugging. You can mention that we had this convo for a faster response.
> 
> Thanks Joel

Where should I open ticket? I think I've already opened it 🤔

**Comment by J0** [comment]
Hey, 

Thanks for quick revert .You can open a ticket at [supabase.help](supabase.help). I did a quick search and am unable to find a related ticket - could we trouble you to share the ticket id if there's an existing open ticket?

Thanks

**Comment by Bartek532** [comment]
> Hey,
> 
> Thanks for quick revert .You can open a ticket at [supabase.help](supabase.help). I did a quick search and am unable to find a related ticket - could we trouble you to share the ticket id if there's an existing open ticket?
> 
> Thanks

The ticket id is 15655465749.

**Comment by J0** [comment]
Thanks

**Comment by J0** [comment]
Hey,

Updating the response here as well for grater visibility - we can't quite reproduce the set up - there should only be one email sent when using an email hook if it is configured properly. 

If anyone is facing similar issues do let us know together with any relevant additional details that might help with reproduction.

Thanks!
