### ISSUE TITLE
Cant add more user with signup endpoint

### ISSUE THREAD

**Issue by hanifjubelio** [supabase/auth#1784]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
after someone push this code so I can use endpoint signup to add more user
https://github.com/supabase/auth/commit/1af203f92372e6db12454a0d319aad8ce3d149e7

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
Just signup new user on endpoint /signup

## Expected behavior
please add authorized address configuration 

## System information

- OS:  MacOS
- Browser (if applies) postman
- Version of supabase-js: -
- Version of Node.js: -

**Comment by cstockton** [comment]
This was an intentional change to protect our shared email service. The easiest way to get around this is adding a custom email provider.
