### ISSUE TITLE
No Such Host

### ISSUE THREAD

**Issue by bunyaminmrcn** [supabase/auth#1814]
`dial tcp: lookup supabase-mail on 127.0.0.11:53: no such host` error on self-hosted supabase. I passed these values to compose
I have `.env` file to set these values with in same directory
```
GOTRUE_SMTP_HOST: ${SMTP_HOST}
GOTRUE_SMTP_PORT: ${SMTP_PORT}
GOTRUE_SMTP_USER: ${SMTP_USER}
GOTRUE_SMTP_PASS: ${SMTP_PASS}
GOTRUE_SMTP_AUTH_METHOD: plain
GOTRUE_SMTP_SENDER_EMAIL: ${SMTP_USER}
GOTRUE_SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
```

**Comment by LinusHojaGER** [comment]
For me it looks like your network isnt configured correctly. I am using the ionos SMTP Server and everything works fine. What are the actual values you are using (not the credentials tho)?

**Comment by bunyaminmrcn** [comment]
It was related network issue. I solved with adding it bridge internal network
