### ISSUE TITLE
What is the environment variable for Authorized Client IDs?

### ISSUE THREAD

**Issue by thurahtetaung** [supabase/auth#1833]
Supabase dashboard has an option to set a comma separated list of client IDs of Android apps, One Tap or Chrome extensions that are allowed to log in to your project.

But I don't see the option to set it among the environment variables of supabase auth for self hosted deployments. Can you clarify on the environment variable value?

**Comment by thurahtetaung** [comment]
Update - 
![image](https://github.com/user-attachments/assets/363c424d-75d9-45e3-ad47-02f2b0089201)

Upon inspecting the api call when updating the oauth values in supabase dashboard, I found that the environment variable is "EXTERNAL_GOOGLE_ADDITIONAL_CLIENT_IDS" but I can't find the reference anywhere in the open-sourced repo. Is this not updated yet or is it not possible for self hosted or local development users to set this?

**Comment by thurahtetaung** [comment]
#1347 is closed with an answer for supabase dashboard but no solutions yet for self hosted or local development.

**Comment by J0** [comment]
Hey @thurahtetaung,

Rest assured that you can set `EXTERNAL_GOOGLE_ADDITIONAL_CLIENT_IDS` on  self-hosted and local development. Could you share more about how you're doing it currently?

On self-hosted it'd be

`EXTERNAL_GOOGLE_ADDITIONAL_CLIENT_IDS`: ... 

like you described a few comments back

**Comment by thurahtetaung** [comment]
It was working using that env value but I was not sure if it's enforcing the authorized client ids or just allowing all client ids. Thank you for pointing out @J0  and @rokk4 , I asked because I couldn't find the value in the example.env file or the readme section.
