### ISSUE TITLE
Resend verification email to nonexistent user doesn't fail

### ISSUE THREAD

**Issue by DreamwareDevelopment** [supabase/auth#1850]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When sending an email to a user that used to exist, but doesn't anymore, I got a false positive. I'd expect the following to fail when the user isn't valid / doesn't exist:
```
await supabase.auth.resend({ email, type: 'signup' })
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. await supabase.auth.resend({ email, type: 'signup' }) with a valid email for an invalid user
2. No error

## Expected behavior

An error should be thrown

## System information

"@supabase/ssr": "^0.5.2"

## Additional context

Really minor issue. I see in the docs:
```
This method will only resend an email or phone OTP to the user if there was an initial signup, email change or phone change request being made.
```
But still, an error would make sense here.

**Comment by cstockton** [comment]
Thanks for the report, this is a deliberate design decision so that you may not use the endpoint to determine if users are registered with the site or not.
