### ISSUE TITLE
Using custom (Unlimited) SMS Provider for sending OTP 

### ISSUE THREAD

**Issue by novanda1** [supabase/auth#385]
# Feature request

Currently, there is just a few SMS Provider, Twilio and Messagebird but they are **expensive** for my country, and there is a local SMS Provider that is **500%++ cheaper.** 

And I believe there is a lot of SMS Provider that cheaper in every country.

https://github.com/supabase/gotrue-js/issues/356

## Describe the solution you'd like

Add option in body request that `gotrue` didn't send the OTP and just give back the OTP code after saving it on the database.  

By that, I can use any SMS Provider to send the OTP code, or even I don't send it via SMS, maybe Whatsapp, or anything else. 

### For example:

```
curl -X POST 'https://tqfkjdmpohkqylveukuhsy.supabase.net/auth/v1/otp' \
-H "apikey: <SERVICE_KEY>" \
-H "Content-Type: application/json" \
-d '{
  "phone": "123123123123", 
  "send_otp": "false"
}'

{"otp_code":"897514"}
```

## Describe alternatives you've considered

Maybe the API that can write the `confirmation_token` 

```
curl -X POST 'https://tqfkjdmpohkqylveukuhsy.supabase.net/auth/v1/confirmation_token' \
-H "apikey: <SERVICE_KEY>" \
-H "Content-Type: application/json" \
-d '{
  "phone": "123123123123", 
  "otp":"<RANDOM>"
}'

{"success":"true"}
```

No need to return an OTP code, since the OTP is created on my end.

**Comment by myemuk** [comment]
Hi, is there a progress here? Really need this feature. Twilio costs 0.2 usd for single sms in my country

**Comment by mamousavi** [comment]
Hey @myemuk, I've already created a PR for this (#558). In the meantime if you're self-hosting you can use [my fork](https://github.com/mamousavi/gotrue/tree/custom_sms_provider) which supports [using a custom SMS gateway](https://github.com/mamousavi/gotrue/blob/custom_sms_provider/README.md?plain=1#L499).

**Comment by myemuk** [comment]
@mamousavi , thanks. Hopefully it will be soon merged

**Comment by novanda1** [comment]
If you need a quick fix just create psql function to duplicate `auth.users` to `public.user` and create psql trigger to run the function each new user `signup`. 

then use RLS (Row Level Security) on your `public.users`.

**Comment by myemuk** [comment]
Any progress here?

**Comment by eduardohr-muniz** [comment]
A suggestion we choose the provider that best serves us, in my case I want to be able to send the code via whatsapp api.

An example is that the subbase generates the token and returns it to us and we send the token via the whatsApp API, sms or whichever provider we want, and the user inserting the right token validates the subbase

**Comment by angelprzz** [comment]
It would be nice to be able to send SMS via Google Cloud's provider.  You get 10,000 successful auths/month for free and it's pretty much the only viable option for many indie developers. I believe many developer decide to stay in Firebase because of that.

**Comment by elcharitas** [comment]
It's 2024, any progress here at all?

**Comment by MJUrian-Learner** [comment]
Is there a workaround on how to do it?

**Comment by J0** [comment]
Hey all,

Thanks for patiently waiting. We've recently released the [send sms hook](https://supabase.com/docs/guides/auth/auth-hooks/send-sms-hook?queryGroups=language&language=http)

Which should allow you to do this. Please give it a spin 

Going to close for now. but don't hesitate to reach us if there are issues

**Comment by abuwho** [comment]
Hello, I am trying to set up the hook in self-hosted mode. 

I have written the edge function

I have the following in my .env file: 
```
ENABLE_PHONE_SIGNUP=true
ENABLE_PHONE_AUTOCONFIRM=false
GOTRUE_HOOK_SEND_SMS_ENABLED=true
GOTRUE_HOOK_SEND_SMS_URI="http://host.docker.internal:8000/functions/v1/send-sms"
GOTRUE_HOOK_SEND_SMS_SECRETS="v1,whsec_***"
```

Problem: the function gets called, but the OTP/Token does not get stored in table. Therefore, the `supabase.auth.verifyOtp` method is not working. Maybe I am doing something incorrectly? 

Here is my edge function `send-sms`: 

```TypeScript
import { crypto } from "https://deno.land/std@0.224.0/crypto/mod.ts";
import { Webhook } from 'https://esm.sh/standardwebhooks@1.0.0'
import { serve } from "https://deno.land/std@0.131.0/http/server.ts"

const LOGIN = "***";
const API_KEY = "***";
const SEND_SMS_HOOK_SECRET = "v1,whsec_***"
const PORT = 4055;

async function createSecret(ts: string): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(ts + API_KEY);
    const hashBuffer = await crypto.subtle.digest('MD5', data);
    return Array.from(new Uint8Array(hashBuffer))
        .map(b => b.toString(16).padStart(2, '0'))
        .join('');
}


async function sendSMS(phoneNumber: string, message: string) {
    const ts = `ts-value-${Date.now()}`;
    const secret = await createSecret(ts);

    const body = JSON.stringify({
        route: 'sms',
        from: 'Admin',
        to: phoneNumber,
        text: message,
    });

    const response = await fetch('https://sms-service.com/api/message', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'login': LOGIN!,
            'ts': ts,
            'secret': secret,
        },
        body: body,
    });

    const json: {
        items: [
            {
                uuid: string,
                status: string,
                status_time: number,
                to: string
            }
        ],
        count: number,
        success: boolean,
    } = await response.json();


    return {
        ...json,
        status: "queued",
        code: response.status,
    }
}

// Start the server
serve(async (req) => {
    const payload = await req.text();
    const base64_secret = SEND_SMS_HOOK_SECRET.replace('v1,whsec_', '')
    const headers = Object.fromEntries(req.headers)
    const wh = new Webhook(base64_secret as string)

    try {
        const { user, sms } = wh.verify(payload, headers)
        const messageBody = `Your OTP is: ${sms.otp}`
        const response = await sendSMS(
            user.phone,
            messageBody
        )

        if (response.status !== 'queued') {
            return new Response(
                JSON.stringify({
                    error: {
                        http_code: response.code,
                        message: "Failed to send SMS :(",
                    },
                }),
                {

                    headers: {
                        'Content-Type': 'application/json',
                    },
                }
            )
        }

        return new Response(
            JSON.stringify({
                error: {
                    http_code: response.code,
                    message: "Code sent successfully",
                },
            }),
            {
                status: 200,
                headers: {
                    'Content-Type': 'application/json',
                },
            }
        )
    } catch (error) {
        return new Response(
            JSON.stringify({
                error: {
                    http_code: 500,
                    message: `Failed to send sms: ${JSON.stringify(error)}`,
                }
            }),
            {
                status: 500,
                headers: {
                    'Content-Type': 'application/json',
                },
            }
        )
    }
}, { port: PORT })

console.log(`SMS Server running on http://localhost:${PORT}`);
```
