### ISSUE TITLE
Add well-defined error codes

### ISSUE THREAD

**Issue by ryansburgoyne** [supabase/auth#842]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently it appears that errors from GoTrue only contain a single property, `msg`, which describes the error. While I could show this message to my users, it would not be localized, and may not match the tone of my app.

## Describe the solution you'd like

I would like it if there were well-documented specific error codes (beyond the HTTP error codes) like `PASSWORD_TOO_SHORT` or `EMAIL_EXISTS` included in error payloads so that I could create my own error messages to present to the user on the application side.

## Describe alternatives you've considered

I could match against the existing `msg` strings, but that seems error-prone and likely to be broken when the language in those strings is updated.

**Comment by ryansburgoyne** [comment]
After further development, I've discovered that some errors do include error codes (`GoTrueError(message: nil, msg: nil, code: nil, error: Optional("invalid_grant"), errorDescription: Optional("Invalid login credentials")`) while others do not (`GoTrueError(message: nil, msg: Optional("Password should be at least 6 characters"), code: Optional(422), error: nil, errorDescription: nil)`.

**Comment by hf** [comment]
This is a known issue and one we're very aware of. It is likely to be one of our biggest priorities in the next year. We'll keep you updated on this issue.

**Comment by NuvensCorporation** [comment]
hello there, it would be nice if you could add the return: user or account does not exist.
Currently when user does not exist it just returns: Invalid login credentials.

**Comment by hf** [comment]
Working on it, main PR here: #1377

**Comment by J0** [comment]
Fixed by #1377

**Comment by FatumaA** [comment]
It appears @hf PR was merged, shouldn't this issue be closed then?

**Comment by NuvensCorporation** [comment]
yes you can close

Em seg., 15 de abr. de 2024 às 07:58, Fatuma Abdullahi <
***@***.***> escreveu:
